### ISSUE TITLE
iphone4浏览器显示，右上角的箭头符号无效

### ISSUE THREAD

**Issue by yinbiao** [P233/3-Jekyll#14]

**Comment by hans-lizihan** [comment]
@yinbiao #16 加下vendor prefix就好

**Comment by P233** [comment]
使用 http://leaverou.github.io/prefixfree/ 处理 vendor prefix 
多谢两位

**Comment by yinbiao** [comment]
加了这个js文件就OK了，感谢

尹彪
15901889112
biao.yin@easyhint.cn
