### ISSUE TITLE
We were unable to load Disqus

### ISSUE THREAD

**Issue by yinbiao** [P233/3-Jekyll#15]

**Comment by P233** [comment]
感谢告知，我在本地 localhost 测试 Disqus 能用，晚上回家后再测试下发布到 GitHub Pages 后的问题

**Comment by yinbiao** [comment]
disqus_shortname: ‘lonay821’  请问这个是我的disqus的用户名吗？


尹彪
15901889112
biao.yin@easyhint.cn

**Comment by P233** [comment]
刚刚跑去 Disqus 后台看了下，这个名字不是用户名，是 discussions 的 shortname

在 Disqus Settings > Admin > Discussions > Settings > install > Universal Code 里 `var disqus_shortname =` 后面的 shortname

请看一下这个是不是 config.yml 里的 shortname？

**Comment by yinbiao** [comment]
哦哦，明白了，非常感谢！

尹彪
15901889112
biao.yin@easyhint.cn

**Comment by P233** [comment]
试试看还有没有问题 :)

另外，看了下你的站，我忘记加  `.gitignore` 了，非常抱歉，建议将下面两个文件从 repo 里删除
```
.sass-cache
_site
```

**Comment by yinbiao** [comment]
恩，好的，谢谢，评论已经正常了

尹彪
15901889112
biao.yin@easyhint.cn
