### ISSUE TITLE
新版本主题，导致旧版本文章中的链接失效

### ISSUE THREAD

**Issue by lzz5235** [P233/3-Jekyll#18]
旧版本中的网址，例如http://localhost:4000/2015/01/22/xxxx.html是这样子的，
在新版本中。加入category分类后，点到每个文章，网址变为http://localhost:4000/category/2015/01/22/xxxx.html
我的文章中经常有引用之前写过文章的习惯，是否有方式去掉这种网址分类？

**Comment by P233** [comment]
Jekyll 默认的 permalink 是 `/:categories/:year/:month/:day/:title.html`，所以可以在 _config.yml 中加入一条

```
permalink: /:year/:month/:day/:title.html
```

请参考 http://jekyllrb.com/docs/permalinks/

另外，rouge 我还需要一点测试，抱歉 :)
